framework:
    messenger:
        default_bus: command_bus

        buses:
            command_bus:
                middleware:
                    - validation
                    - doctrine_transaction

            event_bus:
                default_middleware: allow_no_handlers
                middleware:
                    - doctrine_transaction

        transports:
            sync: 'sync://'
            async: '%env(MESSENGER_TRANSPORT_DSN)%'

        routing:
            'App\Event\UserHasBeenCreatedEvent': async
            'App\Command\SetReactionToPostCommand': async

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
