parameters:
    user_storage: '%kernel.project_dir%/public/files/users'
    media_storage: '%kernel.project_dir%/public/files/media'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
