name: Continuous Integration

on:
    push:
    workflow_dispatch: ~

jobs:
    ci:
        name: "Flux - Continuous Integration"
        runs-on: ubuntu-latest

        strategy:
            fail-fast: true
            matrix:
                php: [ '8.3' ]
                symfony: [ '7.0' ]

        steps:
            -   name: Checkout app
                uses: actions/checkout@v3

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: "${{ matrix.php }}"
                    extensions: intl
                    tools: symfony

            -   name: Create .env file
                run: cp .env.ci .env

            -   name: Install composer dependencies
                run: composer update --no-interaction --no-progress --prefer-dist

            -   name: Run ECS
                run: vendor/bin/ecs check

            -   name: Run PHPUnit
                run: vendor/bin/phpunit
